/*
 * LCD.C
 *
 *  Created on: Sep 10, 2022
 *      Author: hp
 */
#include"LCD.h"
#include "DIO.h"
#include<avr/delay.h>
#include <avr/io.h>

void LCD_SEND_COMMAND(u8 COMMAND)
{
	DIO_SET_PIN_VALUE(LCD_CTRL_PORT,RS,LOW); // SET RS , RW TO 0
	DIO_SET_PIN_VALUE(LCD_CTRL_PORT,RW,LOW);

	DIO_SET_PORT_VALUE(LCD_DATA_PORT,COMMAND); // PORTD IS COMMAND PORT
//	PORTD=COMMAND ;

	DIO_SET_PIN_VALUE(LCD_CTRL_PORT,E,HIGH);  // PULSE IN THE ENABLE PIN
	_delay_ms(10);
	DIO_SET_PIN_VALUE(LCD_CTRL_PORT,E,LOW);  // RS---->>E
	_delay_ms(30);
}

 void LCD_SEND_DATA(u8 DATA)
{
	DIO_SET_PIN_VALUE(LCD_CTRL_PORT,RS,HIGH);  // SET RS 1
	DIO_SET_PIN_VALUE(LCD_CTRL_PORT,RW,LOW);   //  	  RW TO 0
	//PORTA= 0B000000001 ;  -> A0 = 1 , A1 = 0
	DIO_SET_PORT_VALUE(LCD_DATA_PORT,DATA);
//	PORTD = DATA ;
	DIO_SET_PIN_VALUE(LCD_CTRL_PORT,E,HIGH);
	_delay_ms(10);
	DIO_SET_PIN_VALUE(LCD_CTRL_PORT,E,LOW);
	_delay_ms(30);
}
void LCD_INIT(void)
{
	DIO_SET_PIN_DIRECTION(LCD_CTRL_PORT,RS,OUTPUT);
	DIO_SET_PIN_DIRECTION(LCD_CTRL_PORT,RW,OUTPUT);
	DIO_SET_PIN_DIRECTION(LCD_CTRL_PORT,E,OUTPUT);
	DIO_SET_PORT_DIRECTION(LCD_DATA_PORT,OUTPUT);

	_delay_ms(1);
	LCD_SEND_COMMAND(DISPLAY_ON);
	LCD_SEND_COMMAND(DISPLAY_MODE);
	LCD_SEND_COMMAND(CURSOR_AUTO_INCREMENT);
	LCD_SEND_COMMAND(RETURN_HOME);
	LCD_SEND_COMMAND(CLEAR_DISPLAY);
	_delay_ms(300);
}
void LCD_String (u8 *str)		/* Send string to LCD function */
{
	u8 i;
	for(i=0;str[i]!=0;i++)		/* Send each char of string till the NULL */
	{
		LCD_SEND_DATA (str[i]);
	}
}
