/*
 * ADC.h
 *
 *  Created on: Sep 30, 2022
 *      Author: hp
 */

#ifndef ADC_H_
#define ADC_H_

#define ENABLE 1
#define DISABLE 0

#define ADC_CHANNEL0 PIN_0
#define ADC_CHANNEL1 PIN_1
#define ADC_CHANNEL2 PIN_2
#define ADC_CHANNEL3 PIN_3
#define ADC_CHANNEL4 PIN_4
#define ADC_CHANNEL5 PIN_5
#define ADC_CHANNEL6 PIN_6
#define ADC_CHANNEL7 PIN_7

#define PRESCALLER_DIV_2 1
#define PRESCALLER_DIV_4 2
#define PRESCALLER_DIV_8 3
#define PRESCALLER_DIV_16 4
#define PRESCALLER_DIV_32 5
#define PRESCALLER_DIV_64 6
#define PRESCALLER_DIV_128 7

void ADC_INIT(u8 ADC_INTERRUPT_ENABLE , u8 ADC_CHANNEL, u8 PRESCALLER);
void ADC_SWITCH_CHANNEL(u8 ADC_CHANNEL);
void ADC_START_CONVERSION(void);
u16 ADC_READ_VALUE(u8 ADC_INTERRUPT_ENABLE);
u16 ADC_GET_ANALOG_VALUE_mv(u16 DIGITAL_VALUE);
u8 ADC_READ_VALUE_8bits(u8 ADC_INTERRUPT_ENABLE);


#endif /* ADC_H_ */
